### PR TITLE
Add support for MessageLinks in addition to PostIds

### PR DESCRIPTION
**Pull request by Haliax**
This PR addresses #174.

This PR adds the possibility to use copied message-links instead of the PostID for the "attach", "copy", "merge" and "move" commands. ChannelIDs cannot be replaced by a link yet.

### CODE REVIEW

**Comment by Haliax** [comment]
I was not able to find a defined API function to get the link of a message.

Because of that, I haven't added any tests yet.
If there is no function for that, I could create tests with placeholder links instead.

**Comment by gabrieljackson** [comment]
> I was not able to find a defined API function to get the link of a message.

I took a look into the server code on this and don't think we have an easy way to get message links, so let's just build tests with some hardcoded placeholder links.

If you could also update the command help text and the readme with this new option that would be awesome.

**Comment by Haliax** [comment]
I added the descriptions for the command as well as the tests.

The main tests are within the util-tests. As these functions in every command.
Just in case, I also created tests the functions itself.

**Review by gabrieljackson — APPROVED** [review]
Looks good! Thanks for the contribution.

**Pull request merged**
